import { sub } from 'date-fns'
import type { Alert } from '~/types'

const alerts: Alert[] = [{
  id: 1,
  type: 'account_banned',
  category: 'account',
  priority: 'urgent',
  status: 'pending',
  title: 'Account act_100042 has been banned',
  description: 'Meta account act_100042 was banned by the platform. Previously consuming $3,200/day.',
  relatedId: 42,
  relatedType: 'account',
  relatedName: 'act_100042',
  handlerId: null,
  handlerName: null,
  handleResult: null,
  triggeredAt: sub(new Date(), { minutes: 15 }).toISOString(),
  handledAt: null
}, {
  id: 2,
  type: 'balance_low',
  category: 'channel',
  priority: 'urgent',
  status: 'pending',
  title: 'Channel Delta balance critically low',
  description: 'Channel Delta balance is $8,000, estimated to last only 6 days at current consumption rate.',
  relatedId: 4,
  relatedType: 'channel',
  relatedName: 'Channel Delta',
  handlerId: null,
  handlerName: null,
  handleResult: null,
  triggeredAt: sub(new Date(), { hours: 1 }).toISOString(),
  handledAt: null
}, {
  id: 3,
  type: 'idle_account',
  category: 'account',
  priority: 'warning',
  status: 'pending',
  title: '5 accounts idle for 48+ hours',
  description: '5 accounts have had no consumption for over 48 hours. Consider reallocating.',
  relatedId: 0,
  relatedType: 'account',
  relatedName: '5 idle accounts',
  handlerId: null,
  handlerName: null,
  handleResult: null,
  triggeredAt: sub(new Date(), { hours: 3 }).toISOString(),
  handledAt: null
}, {
  id: 4,
  type: 'ban_rate_spike',
  category: 'channel',
  priority: 'warning',
  status: 'claimed',
  title: 'Channel Beta ban rate spiked to 16.7%',
  description: 'Channel Beta 7-day ban rate increased from 8% to 16.7%. Account quality may be declining.',
  relatedId: 2,
  relatedType: 'channel',
  relatedName: 'Channel Beta',
  handlerId: 1,
  handlerName: 'Zhang Wei',
  handleResult: null,
  triggeredAt: sub(new Date(), { hours: 5 }).toISOString(),
  handledAt: null
}, {
  id: 5,
  type: 'usage_rate_low',
  category: 'team',
  priority: 'warning',
  status: 'pending',
  title: 'Team D usage rate below 60%',
  description: 'Team D account usage rate is 60%. 3 accounts are idle. Consider redistribution.',
  relatedId: 4,
  relatedType: 'team',
  relatedName: 'Team D',
  handlerId: null,
  handlerName: null,
  handleResult: null,
  triggeredAt: sub(new Date(), { hours: 6 }).toISOString(),
  handledAt: null
}, {
  id: 6,
  type: 'reconciliation_diff',
  category: 'reconciliation',
  priority: 'info',
  status: 'processing',
  title: 'August reconciliation difference: $2,100',
  description: 'Channel Alpha August bill is $52,100 vs system consumption of $50,000. Difference rate: 4.2%.',
  relatedId: 1,
  relatedType: 'channel',
  relatedName: 'Channel Alpha',
  handlerId: 5,
  handlerName: 'Liu Yang',
  handleResult: null,
  triggeredAt: sub(new Date(), { days: 1 }).toISOString(),
  handledAt: null
}, {
  id: 7,
  type: 'consumption_drop',
  category: 'account',
  priority: 'warning',
  status: 'pending',
  title: 'Account act_100015 consumption dropped 80%',
  description: 'Account act_100015 daily consumption dropped from $2,500 to $500 over the past 3 days.',
  relatedId: 15,
  relatedType: 'account',
  relatedName: 'act_100015',
  handlerId: null,
  handlerName: null,
  handleResult: null,
  triggeredAt: sub(new Date(), { hours: 8 }).toISOString(),
  handledAt: null
}, {
  id: 8,
  type: 'api_sync_failed',
  category: 'system',
  priority: 'info',
  status: 'resolved',
  title: 'Meta API sync recovered',
  description: 'Meta API synchronization was interrupted for 2 hours. Data has been backfilled.',
  relatedId: 0,
  relatedType: 'system',
  relatedName: 'Meta API',
  handlerId: 1,
  handlerName: 'Zhang Wei',
  handleResult: 'API connection restored. Backfilled missing data for 2-hour gap.',
  triggeredAt: sub(new Date(), { days: 1, hours: 4 }).toISOString(),
  handledAt: sub(new Date(), { days: 1 }).toISOString()
}]

export default defineEventHandler(async () => {
  return alerts
})